# Optional: GitHub Actions workflow for automated releases
# This creates pre-built binaries for different platforms

name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'
      
      - name: Build for multiple platforms
        run: |
          # Linux AMD64
          GOOS=linux GOARCH=amd64 go build -o neno-linux-amd64 .
          
          # Linux ARM64
          GOOS=linux GOARCH=arm64 go build -o neno-linux-arm64 .
          
          # macOS AMD64
          GOOS=darwin GOARCH=amd64 go build -o neno-darwin-amd64 .
          
          # macOS ARM64 (M1/M2)
          GOOS=darwin GOARCH=arm64 go build -o neno-darwin-arm64 .
          
          # Windows AMD64
          GOOS=windows GOARCH=amd64 go build -o neno-windows-amd64.exe .
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            neno-linux-amd64
            neno-linux-arm64
            neno-darwin-amd64
            neno-darwin-arm64
            neno-windows-amd64.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

